### ISSUE TITLE
Implement client-side logout functionality

### ISSUE THREAD

**Issue by meinte** [losol/eventuras-front#11]
Currently there is no logout callback setup - meaning any remaining local session is not 'cleaned' up in the frontend. To reproduce, log out then log back in again - it does not require any credentials.

**Comment by Rados51** [comment]
[Seems like an issue with Auth0 as there is not direct way to logout from it complety, without visiting their](https://github.com/nextauthjs/next-auth/issues/836)

https://github.com/nextauthjs/next-auth/issues/1384

**Comment by losolio** [comment]
Is this the web edition of The Hotel California? “You can check-out any time you like, but you can never leave!"

**Comment by meinte** [comment]
I'm picking this up today as it's causing a bit of confusion along with refresh tokens not working correctly
