### ISSUE TITLE
Datagrid pagination

### ISSUE THREAD

**Issue by meinte** [losol/eventuras-front#138]
The datagrid currently does not support pagination - the API does. Need to support server-side-pagination through the frontend.

**Comment by losolio** [comment]
There is a clientside pagination in the current code, which preferably should stay together with server side!

**Comment by meinte** [comment]
I think it would behave odd to enable both at the same time - thinking of splitting it up in seperate components

**Comment by meinte** [comment]
the only point in doing clientside pagination is if we want to pull in -all- data for a certain resource and do things client-side, to save on api calls, but I wonder if it is a good strategy

**Comment by losolio** [comment]
if it is not complicated it would be cool to have a choice between client side and server side pagination. Never at the same time, but I see some use cases on small data set!
