### ISSUE TITLE
Feature: Let users register for events, and customize products

### ISSUE THREAD

**Issue by losolio** [losol/eventuras-front#15]
As a end user I can register to events, so that I can have fun!

This task includes to provide registration to events and customization of ordered products: Implement the functionality to allow participants to register for events and customize their ordered products.

## Event registration flow

Before flow: 

1. Start page. Clicks on event card
2. On event details page (ie https://eventuras.losol.io/events/5 ): User clicks register for event. 

Registration flow: 

1. Ensure user is logged in. If not logged in, send user to login. 
2. GET **`https://api.eventuras.losol.io/v3/events/5/products`**  to get products to list. 
    1. Mandatory products on top. User should not be able to deselect those. 
    2. if `enableQuantity` is true: use a integer input. if `minimumQuantity` is set, ensure validation has a minimum rule
    3. for other fields: use checboxes. 
    4. ProductVariants is not currently in use
3. After the user has customized his products, we will collect some more information about the user:
    1. name & email  - get this with GET from `v3/users/me`. User should not be able to edit these fields
    2. text fields: zip: string, city: string, country: string
    3. radio buttons: Let the user choose between E-mail and Electronic invoice for now. Which maps to Paymentproviders: PowerOfficeEmailInvoice**,** PowerOfficeEHFInvoice. (Need to extend this later). 
    4. userId and eventId is needed, but no user input is needed. 
4. do a POST to `v3/registrations`: { 
"customer": {
"vatNumber": "string",
"name": "string",
"email": "[[user@example.com](mailto:user@example.com)](mailto:user@example.com)",
"zip": "string",
"city": "string",
"country": "string",
"invoiceReference": "string"
},
"notes": "string",
"type": "Participant",
"paymentMethod": "EmailInvoice",
"userId": "string",
"eventId": 2147483647,
**"createOrder": true**
}.
You will get an registration with an Id back! Keep that registration id 🙂
5. Now we need to lookup the orders for the new registrations… Using the id we should now have a order with all mandatory products when doing GET `/v3/registrations/{RegistrationId}/orders`. Note the orderId. 
6. Now this is getting a little complicated, but we should update the order for the registration, and add the optional products the user has selected to the order, possibly with a PUT to `/v3/orders/{OrderId}`
7. After all things done: we could show a confirmation to the user!

**Comment by losolio** [comment]
Sketches: https://www.figma.com/file/jBmkvkH4YhVslEZiersuzR/register-for-event?type=design&node-id=0%3A1&mode=dev 

<img width="858" alt="image" src="https://github.com/losol/eventuras-front/assets/17168367/a78c8408-5652-418a-bbea-553d8b294834">
<img width="594" alt="image" src="https://github.com/losol/eventuras-front/assets/17168367/e05595e8-fadb-4e31-8e9d-47be3dac2460">

**Comment by losolio** [comment]
Now the api provides some more relevant info that was missing, @meinte :) 
Update the `@losol/eventuras` to version 0.3.1 to get this typed

<img width="721" alt="image" src="https://github.com/losol/eventuras-front/assets/17168367/ed31b74e-23e6-48cd-a61e-c49f001b44d6">

**Comment by losolio** [comment]
@meinte I tried to make a clearer description of the flow now in the issue description, hopefully it is better!

@yura-b In the old Api from the `Eventuras.Web`project, we did expose a really useful method, where the frontend, only posts a List<OrderVM> to the backend like this. 

```

   public class OrderVM
    {
        public int ProductId { get; set; }
        public int? VariantId { get; set; }
        public int Quantity { get; set; } = 1;
    }

Could you think about how we can make a small backend for frontend in a RESTful way? it would be great if the frontend could just post something like 

```json
{
  "lines": [
    {
      "productId": 1,
      "productVariantId": 0,
      "quantity": 1
    },
    {
      "productId": 2,
      "productVariantId": 0,
      "quantity": 5
    }
  ]
}
```

and then the backend could ensure that orders that are not invoiced will just be updated. If orderlines are invoiced, we will need to make an correction order to make sure that the sum of products ordered for all orders for a registration equals to the amount of each product specified in the object from the frontend. Take a look at the _createOrUpdateOrderAsync for inspiration.

**Comment by losolio** [comment]
and finally some updated docs: 

https://github.com/losol/eventuras/blob/main/docs/developer/Business_logic/Event_registration_flow.md
https://github.com/losol/eventuras/blob/main/docs/developer/Business_logic/Order_management.md

**Comment by meinte** [comment]
Ill get on to it, I'll upgrade the app first as discussed (https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration)

**Comment by Rados51** [comment]
@meinte I made a PR for this already.
If it is possible to create a new `next-app` branch, I will merge it there.

**Comment by Rados51** [comment]
> Ill get on to it, I'll upgrade the app first as discussed ([nextjs.org/docs/app/building-your-application/upgrading/app-router-migration](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration))

@meinte I made a PR for this already.
If it is possible to create a new `next-app` branch, I will merge it there.

**Comment by losolio** [comment]
@meinte @Rados51 I was originally thinking on waiting on the app router migration, but #53 is promising, and if we could get #53 working, I think we should merge it down to main as soon as possible!

**Comment by meinte** [comment]
feel free to merge it!

**Comment by meinte** [comment]
Picking this up today on a new branch.

**Comment by meinte** [comment]
@Rados51 the app router was reverted on main as it was giving quite a few mysterious issues - for now that was branched to experimental/app-router branch

**Comment by Rados51** [comment]
> @Rados51 the app router was reverted on main as it was giving quite a few mysterious issues - for now that was branched to experimental/app-router branch

Which issues?
