### ISSUE TITLE
Event registration fails

### ISSUE THREAD

**Issue by losolio** [losol/eventuras-front#153]
**Describe the bug**
Gets an 500 error when registering for events

**Steps to reproduce**
1. see event
2. register for event button
3. fill in details
4. select products
5. register
6. sees 
7. 
<img width="493" alt="image" src="https://github.com/losol/eventuras-front/assets/17168367/7f87ff53-e756-45a8-aa38-4564c90d27cd">

in the log: Response constructor: Invalid response status code 204
 ⨯ TypeError: Response constructor: Invalid response status code 204
    at webidl.errors.exception (node:internal/deps/undici/undici:1376:14)
    at initializeResponse (node:internal/deps/undici/undici:6968:31)
    at new Response (node:internal/deps/undici/undici:6779:9)
    at new NextResponse (/var/task/.next/server/chunks/2682.js:1:4440)
    at forwarder (/var/task/.next/server/app/api/eventuras/[...path]/route.js:1:1857)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapRouteHandlerWithSentry.js:50:32

**Expected behavior**
complete registration

<img width="715" alt="image" src="https://github.com/losol/eventuras-front/assets/17168367/ca86391e-c458-468c-94f4-b2d6293ed1f8">

**Comment by yura-b** [comment]
Seems like 500 comes from backend

**Comment by meinte** [comment]
the 204 makes me suspect it could be frontend handling response as well :/ Ill take a look today

**Comment by losolio** [comment]
Thanks.. I will work today with adding more logging to the backend so it would be easier to troubleshoot with access to backend logs as well! Could not find any 500 errors in the backend log, however...

**Comment by meinte** [comment]
> Seems like 500 comes from backend, will take a look too.
> 
> However I need some more information on the bug. Or some logs. Currently unable to reproduce on stage (eventuras.losol.io)

what are the situations where, on registering for an event, the server would return a 204? So I can reproduce more easily

**Comment by meinte** [comment]
@losolio does the offending deployment include this change? https://github.com/losol/eventuras-front/commit/68192e28d565e04a294e00b3ba0d0cdb7f451f8d . It was introduced to sidestep issues where parsing the response might actually throw an error.

**Comment by losolio** [comment]
I will try to reproduce, and get some more logs!! Stay tuned! 

The code deployed was the latest main, after that commit - https://github.com/losol/eventuras-front/commit/4ad87c0609e5c916e51288ad819580c47f1db3d1

**Comment by meinte** [comment]
is this backend related then?

**Comment by losolio** [comment]
@meinte think so! 

@yura-b Feel free to share your thoughts? Could it be related to the ICurrentOrganizationAccessorService ? Or something in the admin check?  Not sure why it says that orgid is not specified.

**Comment by losolio** [comment]
Might be related to [this issue](https://github.com/losol/eventuras-front/issues/157).

**Comment by yura-b** [comment]
Inspecting.
From provided logs i can say those are 400 responses, not 500

**Comment by losolio** [comment]
Closing as resolved
