### ISSUE TITLE
Remove dependency on axios

### ISSUE THREAD

**Issue by losolio** [losol/eventuras-front#21]
To ensure we do use [next.js data fetching capabilities](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching), we should remove the dependency on axios.

**Comment by baroiSubhra** [comment]
Hi @losolio , I am interested in contributing to this project, can I work on this issue ??

**Comment by losolio** [comment]
Thanks for your interest in contributing to this, @baroiSubhra. For this issue we have allready started development, but keep following the repo for lots of opportunities for contributing in the future 🤩

**Comment by meinte** [comment]
Since using the SDK, there are no longer any Axios references in the frontend. All that is required is removal of Axios from package.json
